# Generated by Django 3.1.7 on 2021-04-09 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedRides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riderLocation', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('addSupport', models.CharField(max_length=200, null=True)),
                ('driver', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='driver', to=settings.AUTH_USER_MODEL)),
                ('riderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
