# Generated by Django 3.1.7 on 2021-04-11 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0002_auto_20210402_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riderpending', to=settings.AUTH_USER_MODEL),
        ),
    ]
