# Generated by Django 3.1.7 on 2021-04-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20210411_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tip',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
