# Generated by Django 3.1.7 on 2021-04-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_post_tip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tip',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
