# Generated by Django 3.1.7 on 2021-04-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_auto_20210414_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tip',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
